### ISSUE TITLE
[REQUEST] Callback if blade not found

### ISSUE THREAD

**Issue by zaingithub** [ventoviro/windwalker-renderer#5]
Hi, Thanks for create this awesome renderer template :)

I want to ask, can you make a function inside BladeRenderer Class or whatever, to make a callback if a blade rendered is not found in the views path.

I have some static blade like header (including meta data etc) also footer (consist of analytic code etc), and i want to implement a Theme using blade.

my theme views blade is inside the theme self directory, and i want to place the header & footer in the folder theme

- views
-- theme
--- default_theme
--- simple_theme
--- include
---- header.blade.php
---- footer.blade.php

Thanks :)

**Comment by asika32764** [comment]
It's seems you can add multiple paths to find the header and footer file

```php
$renderer->addPath('theme');
$renderer->addPath('theme/include');
$renderer->addPath('theme/layouts');
```

Do I missunderstand any part of your request?

**Comment by zaingithub** [comment]
Awesome! Thanks for help me, Friends :)
Keep improving, like your project so much! xoxo

**Comment by asika32764** [comment]
👍
