### ISSUE TITLE
passing values through url to other view

### ISSUE THREAD

**Issue by scamexdotexe** [ventoviro/windwalker-renderer#6]
Hi,
I'm just curios on how to go about passing variables or values to another view in blade?

**Comment by asika32764** [comment]
If you use `@include`, try `@include('other.view, ['foo' => $foo, 'bar' => $bar]')`

**Comment by scamexdotexe** [comment]
What I want to do is click through a link say for example this:

`<a href="{{url('index')}}">Go to index page</a>`

A traditional way to pass information to another page or view is like this:

`<a href="index.php?id=1&name=Jack">Go to index page</a>`

But I'm not so sure on how to do it now with blade.

**Comment by asika32764** [comment]
The `url()` function not belongs to Blade, it belongs to Laravel's routing package.

So you must implement it yourself or install Laravel Routing.
