### ISSUE TITLE
Package for Windwalker Renderer 3.4.9 contains the wrong files

### ISSUE THREAD

**Issue by maxiwheat** [ventoviro/windwalker-renderer#8]
[Package for Windwalker Renderer 3.4.9](https://github.com/ventoviro/windwalker-renderer/releases/tag/3.4.9) is not the correct package, it contains the database package, not the renderer, which breaks every application trying to use this specific project via composer.

**Comment by asika32764** [comment]
Fixed, please try again: https://github.com/ventoviro/windwalker-renderer/tree/3.4.9
